### ISSUE TITLE
[Tracking] More Configuration options

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#317]
a lot of people want some things slightly different then the goal of this mods good examples for that are the Alicorn survival ban and which species can stand on clouds so I would propose that these things would be able to make possible with config file, gamerule, unicopia subcommand or datapack

this is a tracking issue so everyone who wants certain things to be configurable please reply below

**Comment by PoneyClairDeLune** [comment]
https://github.com/team-cloudchaser/Patchiopia

**Comment by PoneyClairDeLune** [comment]
Since I'm too lazy to comment on the specifics by just pasting the link to the README of the patched version, which got removed, I'm posting again to see if it will be removed again.

- [ ] Enable/disable "Stressful".
- [ ] Enable/disable lovesickness for changelings. When disabled, normal foodstuff is less filling, while fruits are the same. Sugary treats get changelings hyper like batponies' mango rush. I guess this should be implemented as dietary profiles instead?
- [x] All winged species' ability to interact with cloud blocks.
- [x] Stackable bottles.
- [x] Stackable jars.

To be fair, next time a warning would be nice, instead of flat out removal without any explanation. I'm not trying to advertise a fork following a different lore or anything, just too lazy to copy the changes from there.

**Comment by Sollace** [comment]
1. Stressful was already rewritten to be useful. You only get it when a hostile mob can see you.
2. The last update made a TON of stuff edible for changelings. They are carnivors. If they don't have access to love they can eat raw, cooked, and rotten meat. They can also eat items from the "insect" food category which has spider eyes, and butterflies.

Raw and cooked fish has reduced negative effects compared to other things.

3. This is for a canon reason, and a core function of the clouds. Only ponies with pegasus magic can touch them. That is _the_ signature feat of the race.

No one has asked to make bottles and jars stackable. Bottles are a vanilla item. What is the relevance of changing them?

**Comment by MimzyFang** [comment]
I dont think wee need to add modifying stack sizes as that would be possible using datapacks starting 1.20.5/1.21

**Comment by MimzyFang** [comment]
The issue is in general about things that should be configured while some of the things were addressed there might be things in the future that could be nice as a config option and should be posted here
